### ISSUE TITLE
How does this compare to Remill and McSema?

### ISSUE THREAD

**Issue by pgoodman** [Microsoft/llvm-mctoll#1]
Remill lifts x86, amd64, and AArch64 instructions to LLVM bitcode: https://github.com/trailofbits/remill

McSema uses Remill and has plugins with IDA Pro, Binary Ninja, and DynInst to lift whole program binaries to LLVM bitcode: https://github.com/trailofbits/mcsema

**Comment by pgoodman** [comment]
For example, this is what Remill-lifted bitcode looks like: https://github.com/trailofbits/remill/tree/master/tools/lift

And this is the approach taken by Remill to lift to bitcode:
http://www.petergoodman.me/docs/cppcon-poster1-2018.pdf
http://www.petergoodman.me/docs/cppcon-poster2-2018.pdf

As far as I ca tell, llvm-mctoll takes a superficially similar approach to McSema version 1, which disassembled bytes to `llvm::MCInst`, then manually generated bitcode via LLVM IR creation APIs.

**Comment by bharadwajy** [comment]
Thanks for taking a look at llvm-mctoll and for your comments, Peter.

This is an initial attempt to raise X64 binaries solely using the LLVM infrastructure. My wildest dream is to be able build support/framework such that one can "just" run the traditional LLVM back-end compilation passes in the reverse order to raise/lift the binary of any architecture with an LLVM backend :-) 

At this point llvm-mctoll may not even be close to the maturity level of McSema. We hope the continuing work on llvm-mctoll will make it a viable tool as well.

I consider this to be yet another attempt to address the problem at hand with minimal dependencies other than LLVM. We'd love to learn from your development experiences (with McSema) and insights so that this tool might be able to mature faster.

All feedback is welcome.

**Comment by dguido** [comment]
> At this point llvm-mctoll may not even be close to the maturity level of McSema. We hope the continuing work on llvm-mctoll will make it a viable tool as well.

This seems like a lot of effort to eventually achieve clone mcsema, which itself is open-source. Is there something about mcsema that you need or want changed? You mentioned minimal dependencies. What dependencies are you specifically concerned about? Maybe it makes more sense to focus on helping us eliminate those dependencies than trying to reinvent the entire frame.

**Comment by aaronsm** [comment]
There are a number of related projects leveraging llvm in interesting ways like mcsema, llbt, mambo, bolt, panda, revamb, retdec, fcd, gensim. It's a good topic for a bof at the next llvm developer meeting.  Maybe we can discuss there.

**Comment by dguido** [comment]
We tried to summarize the current state of lifters in this table:
https://github.com/trailofbits/mcsema#comparison-with-other-machine-code-to-llvm-bitcode-lifters
