### ISSUE TITLE
Unknown prototype for function : _ZNSaIcEC1Ev

### ISSUE THREAD

**Issue by EricCD-S** [microsoft/llvm-mctoll#176]
I try to raise an executable file in klee docker and i meet this issue. My environment is ubuntu18.04.What can i do to solve this?

**Comment by bharadwajy** [comment]
Thanks for your interest in the project.

Unmangling the function symbol indicates that it is `std::allocator<char>::allocator()`. A couple of observations in this regard:
1. `llvm-mctoll` still lacks explicit support to raise C++ binaries and hence is not tested to raise them.
2. Incase you encounter such message when raising C binaries, the way to address it is to pass the header file path as a command-line option using `-I`. However, in your case this would not work because of the above stated reason.
