### ISSUE TITLE
Support for __stack_chk_fail

### ISSUE THREAD

**Issue by chinmaydd** [microsoft/llvm-mctoll#55]
Hello all!

On certain Linux distributions, gcc enables stack protection by default. This makes the compiler introduce canaries and add `__stack_chk_fail` function to detect overflows. `llvm-mctoll` fails on raising basic binaries compiled with `-fstack-protector`. I guess one could add handling in `ExternalFunctions.cpp` or add a note to the `README` to inform the user. I would be interested in hearing your thoughts on fixing this.

**Comment by bharadwajy** [comment]
Thanks for flagging this issue. 

I'd suggest that adding `__stack_chk_fail` as external function would be a correct solution in the short term. I would really prefer to handle binaries with stack protection as well and **not** add a note to README as a caveat (if that is what you meant).

That said, as a quick follow on to the short term fix above, it would be interesting to figure out a way to abstract it away since it appears to me that the stack protection mechanism is a tad lower than LLVM IR abstraction and is a runtime issue not exactly related to the binary being raised. Further I think it is a runtime addition to the binary, similar to `__libc_csu_init`, `__do_global_dtors_aux` etc., that are ignored while raising a binary. I realize that `__stack_chk_fail` has a different purpose and hence think may need additional analysis at callsite for proper abstraction - in contrast the other runtime call targets that are simply ignored during the process of raising.

Any help with handling this and/or feedback is highly appreciated.

**Comment by bharadwajy** [comment]
Closing due to lack of response. Reopen if needed.
