### ISSUE TITLE
Unable to checkout using LLVMVersion.txt hash

### ISSUE THREAD

**Issue by testhound** [microsoft/llvm-mctoll#66]
When trying to checkout the hash in LLVMVesion.txt:

git checkout dca920a904c27f4c86e909ef2e4e343d48168cca

An error is received.

fatal: reference is not a tree: dca920a904c27f4c86e909ef2e4e343d48168cca

I think the issue is the commit was reverted.

**Comment by bharadwajy** [comment]
Thanks for the feedback.

The [commit](https://github.com/llvm/llvm-project/commit/dca920a904c27f4c86e909ef2e4e343d48168cca) exists in the repo. Yes, it does seem to be [reverted](https://github.com/llvm/llvm-project/commit/c025235e962e2cec58e47a572eac3f88a55f3a1e), but git history is not rewritten.

Just clone the entire llvm-project instead of a shallow clone. The commit dca920a904c27f4c86e909ef2e4e343d48168cca appears to be more than 500 commits old. A shallow clone with depth 500 hence does not include that commit.
 
I'll modify the README.md instructions to drop the argument `--depth 500` to `git clone`.

Feel free to reopen if you still encounter problems.
